# Generated by Django 2.1.7 on 2022-02-21 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='地域')),
            ],
        ),
        migrations.CreateModel(
            name='bearShippingFee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='送料負担')),
            ],
        ),
        migrations.CreateModel(
            name='itemCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='商品カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='itemCategoryDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='詳細カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='itemCondition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='状態')),
            ],
        ),
        migrations.CreateModel(
            name='itemList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='画像1')),
                ('image2', models.CharField(blank=True, max_length=300, verbose_name='画像2')),
                ('image3', models.CharField(blank=True, max_length=300, verbose_name='画像3')),
                ('image4', models.CharField(blank=True, max_length=300, verbose_name='画像4')),
                ('image5', models.CharField(blank=True, max_length=300, verbose_name='画像5')),
                ('image6', models.CharField(blank=True, max_length=300, verbose_name='画像6')),
                ('image7', models.CharField(blank=True, max_length=300, verbose_name='画像7')),
                ('image8', models.CharField(blank=True, max_length=300, verbose_name='画像8')),
                ('image9', models.CharField(blank=True, max_length=300, verbose_name='画像9')),
                ('image10', models.CharField(blank=True, max_length=300, verbose_name='画像10')),
                ('name', models.CharField(max_length=80, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='値段')),
                ('description', models.CharField(max_length=2000, verbose_name='商品説明')),
                ('shippingFee', models.IntegerField(blank=True, verbose_name='送料')),
                ('sellDate', models.DateTimeField(verbose_name='出品日')),
                ('lastUpdate', models.DateTimeField(verbose_name='最終更新日')),
                ('bearShippingFee', models.ForeignKey(max_length=1, on_delete=django.db.models.deletion.CASCADE, to='shop.bearShippingFee', verbose_name='送料負担')),
                ('category', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='shop.itemCategory', verbose_name='カテゴリー')),
                ('seller', models.ForeignKey(max_length=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='出品者')),
                ('shipArea', models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.CASCADE, to='shop.area', verbose_name='発送元地域')),
            ],
        ),
        migrations.CreateModel(
            name='shippingMethod',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='配送方法')),
            ],
        ),
        migrations.CreateModel(
            name='shippingTime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='発送までの日数')),
            ],
        ),
        migrations.CreateModel(
            name='userList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名前')),
                ('password', models.CharField(default='password', max_length=400, verbose_name='パスワード')),
                ('picture', models.ImageField(blank=True, max_length=2000, null=True, upload_to='media', verbose_name='写真')),
                ('description', models.CharField(blank=True, max_length=4000, verbose_name='自己紹介')),
                ('follower', models.IntegerField(blank=True, verbose_name='フォロワー')),
                ('following', models.IntegerField(blank=True, verbose_name='フォロー中')),
                ('listingCount', models.IntegerField(blank=True, verbose_name='出品数')),
                ('rate', models.IntegerField(blank=True, verbose_name='評価')),
                ('registDate', models.DateTimeField(blank=True, verbose_name='登録日')),
                ('lastUpdate', models.DateTimeField(blank=True, verbose_name='最終更新日')),
            ],
        ),
        migrations.AddField(
            model_name='itemlist',
            name='shippingMethod',
            field=models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.CASCADE, to='shop.shippingMethod', verbose_name='配送方法'),
        ),
        migrations.AddField(
            model_name='itemlist',
            name='shippingTime',
            field=models.ForeignKey(max_length=1, on_delete=django.db.models.deletion.CASCADE, to='shop.shippingTime', verbose_name='発送までの日数'),
        ),
        migrations.AddField(
            model_name='itemlist',
            name='status',
            field=models.ForeignKey(max_length=1, on_delete=django.db.models.deletion.CASCADE, to='shop.itemCondition', verbose_name='商品状態'),
        ),
    ]
