# Generated by Django 2.1.7 on 2022-02-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220221_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='area',
            new_name='ModelArea',
        ),
        migrations.RenameModel(
            old_name='bearShippingFee',
            new_name='ModelBearShippingFee',
        ),
        migrations.RenameModel(
            old_name='itemCategory',
            new_name='ModelItemCategory',
        ),
        migrations.RenameModel(
            old_name='itemCategoryDetail',
            new_name='ModelItemCategoryDetail',
        ),
        migrations.RenameModel(
            old_name='itemCondition',
            new_name='ModelItemCondition',
        ),
        migrations.RenameModel(
            old_name='itemList',
            new_name='ModelItemList',
        ),
        migrations.RenameModel(
            old_name='shippingMethod',
            new_name='ModelShippingMethod',
        ),
        migrations.RenameModel(
            old_name='shippingTime',
            new_name='ModelShippingTime',
        ),
        migrations.DeleteModel(
            name='userList',
        ),
    ]
