# Generated by Django 2.1.7 on 2022-02-24 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220223_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelListStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='出品状態')),
            ],
        ),
        migrations.CreateModel(
            name='ModelShipStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='配送状態')),
            ],
        ),
        migrations.CreateModel(
            name='ModelTransactionList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionStartDate', models.DateTimeField(verbose_name='取引開始日')),
                ('lastUpdate', models.DateTimeField(verbose_name='最終更新日')),
                ('buyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyerId', to=settings.AUTH_USER_MODEL, verbose_name='購入者ID')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ModelItemList', verbose_name='商品ID')),
                ('sellerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerId', to=settings.AUTH_USER_MODEL, verbose_name='出品者ID')),
                ('shipStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipStatus', to='shop.ModelShipStatus', verbose_name='配送状態')),
                ('transactionStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionStatus', to='shop.ModelShipStatus', verbose_name='取引状態')),
            ],
        ),
        migrations.CreateModel(
            name='ModelTransactionStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='取引状態')),
            ],
        ),
    ]
