# Generated by Django 2.1.7 on 2022-02-24 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_modelitemlist_liststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltransactionlist',
            name='transactionStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionStatus', to='shop.ModelTransactionStatus', verbose_name='取引状態'),
        ),
    ]
