# Generated by Django 2.1.7 on 2022-02-24 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20220224_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelitemlist',
            name='buyer',
            field=models.ForeignKey(default=2, max_length=8, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='購入者'),
        ),
        migrations.AlterField(
            model_name='modelitemlist',
            name='seller',
            field=models.ForeignKey(max_length=8, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='出品者'),
        ),
    ]
