# Generated by Django 2.1.7 on 2022-02-25 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_modelitemlist_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelitemlist',
            name='shipStatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.ModelShipStatus', verbose_name='配送状態'),
        ),
        migrations.AddField(
            model_name='modelitemlist',
            name='transactionStartDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取引開始日'),
        ),
        migrations.AddField(
            model_name='modelitemlist',
            name='transactionStatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.ModelTransactionStatus', verbose_name='取引状態'),
        ),
    ]
