# Generated by Django 2.1.7 on 2022-02-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220225_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelitemlist',
            name='transactionId',
        ),
    ]
