# Generated by Django 2.1.7 on 2022-02-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220225_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelitemlist',
            name='transactionStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ModelTransactionStatus', verbose_name='取引状態'),
        ),
    ]
