# Generated by Django 2.1.7 on 2022-02-25 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20220225_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelitemlist',
            name='buyer',
            field=models.ForeignKey(blank=True, max_length=8, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='購入者'),
        ),
    ]
